root_url = "https://vpm.vlang.io"
is_dev = false
dev_user = "test_user"

[jwt]
secret = "some_very_secure_secret"

[github]
client_id = ""
secret = ""

[http]
port = 8081

[postgres]
host = "db"
port = 5432
user = "vpm"
password = "vpm"
db = "vpm"

